### ISSUE TITLE
Beta version doesnt work

### ISSUE THREAD

**Issue by redtyper** [kanji-karanja/bettingtipske#2]
Hello, 
New dashboard for clients dont work. No reactions for clicked buttons. This is message for console google chrome : 

```
Uncaught TypeError: Cannot read property 'querySelector' of null
    at tooltip (chartist-plugin-tooltip.min.js:56)
    at f.<anonymous> (chartist.js:1656)
    at Array.forEach (<anonymous>)
    at f.h (chartist.js:1652)
```

**Comment by kanji-karanja** [comment]
Thanks for the interest.
Will push for the latest git commit.

**Comment by kanji-karanja** [comment]
Try using the branch v0.0.10-a-1 it has the lastest changes and everything works as fine

**Comment by redtyper** [comment]
Thanks. 
This is awesome :) 
Are you planning in future versions to add paypal payment?
a lot of work with it would be?

**Comment by kanji-karanja** [comment]
Currently working with Kenya's MPESA API for transaction purposes. In Future, more payment methods will be added and included.
